apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: scry-audit
  namespace: scry
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  # storageClassName: standard       # set per-cluster default if needed
