{{- if not .Values.existingSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "scry.secretName" . }}
  labels: {{- include "scry.labels" . | nindent 4 }}
type: Opaque
stringData:
  servers.yml: |-
    {{- .Values.serversYaml | nindent 4 }}
  {{- if .Values.clientsYaml }}
  clients.yml: |-
    {{- .Values.clientsYaml | nindent 4 }}
  {{- end }}
{{- end }}
